### ISSUE TITLE
Sleeping device?

### ISSUE THREAD

**Issue by PetrDa** [RobTillaart/AM232X#13] opened 2021-03-21 16:38 UTC
Hi Rob,
I have tested the library with ESP8266. Both examples first reported that there is no sensor, but after soft WDT reset sensor was present (with this code):
` if (! AM2320.begin(SDA, SCL) )`
 ` {`
`    Serial.println("Sensor not found");`
`    while (1);`
`  }`

 Then I changed the example code to this:
`  AM2320.begin(SDA, SCL);`
`  if (! AM2320.isConnected() )`
`  {`
`    Serial.println("Sensor not found");`
`    while (1);`
`  }`

And it reported the sensor at the first run. It seems that sensor is somehow sleeping and it is necessary to call it twice to answer.
The same result was when I used the I2C device scanner code. When I made two consecutive reads from the same address the device was discovered. 
What about to double the read of the device in the proc ::isConnected() to avoid this issue? 
(You do the similar in _wakeup() proc.)

**Comment by RobTillaart** [comment] 2021-03-21 20:17
Interesting find, I will need to check the datasheet if I can find anything related to this behaviour. 
Might take a few days. 

Your solution is quite practical, thanx

**Comment by RobTillaart** [comment] 2021-03-22 08:59
Your observation is confirmed by the datasheet of the AM2321 (and AM2320)

From AM2321.PDF

_After sending the sensor data, trigger a temperature and humidity measurements; After the measurement is completed, the recording temperature and humidity values, then completed a communication, **the sensor automatically goes to sleep**; therefore, as long unread sensors continuously read the second sensor, in the second reading of the temperature and humidity back to the latest value (minimum interval of continuous reading 2S)._

and 

_8.3.3 Single-bus communication timing
Hosts (MCU) sends a start signal (**data bus SDA low for at least 800μs**) After, AM2321 transition from sleep mode to high-speed mode. After completion, the master start signal, AM2321 transmit a response signal, the data sent from the data bus 40Bit SDA serial high byte is transmitted first; data is sequentially transmitted high humidity, low humidity, high temperature, low temperature, the parity bit , sent a message to trigger the end of data collection, collecting sensor automatically transferred to the **end of the sleep mode** until the next traffic coming._

So there is definitely a sleep modus.
I expect that the first communication is enough to wake it up, however the sensor has no time to make a measurement, so only after that it can respond. I do not recall seeing this sleep mode during my tests, probably because I wasn't looking for it.

To be continued.

**Comment by RobTillaart** [comment] 2021-03-30 13:41
Finally some time ...

would this sound like a the interfaces
```cpp
//  returns true if device-address is found on I2C bus. As the device can be in sleep modus it will retry a number of times.
bool isConnected(uint8_t retries = 1);
```
or

```cpp
//  returns true if device-address is found on I2C bus. As the device can be in sleep modus it will retry for X milliseconds.
bool isConnected(uint16_t milliseconds = 1000);
```

I prefer the latter as it is more defined in terms of what can be expected.  
If the I2C speed is higher the nr of retries might be still not be enough.

**Comment by RobTillaart** [comment] 2021-03-30 14:13
Added develop stream cba738a that has the improved **bool isConnected(timeout)** + **bool wakeUp()** in the interface.
Tests are running. 

Can you please verify it works for you?

**Comment by PetrDa** [comment] 2021-03-30 14:53
Hi Rob, 
any of the two solutions are fine for me (I even made it working with current driver release).
Side note: I am experiencing strange behaviour of the sensor. After few hours it disapears and appears again after its power off (reboot does not help). Maybe it is a wrong piece, I try another one in next days, but all of then I have are from one batch from aliexpress purchase, so even when second fails it can be the same sensor hw problem. (I am sure that I2C bus is Ok since at the same time SHT31, BME280, MCP23017 and ADS1115 continue to work correctly on the same pcb board).

**Comment by RobTillaart** [comment] 2021-03-30 17:23
Good to hear both options are ok,
Don't think the  wakeUp()  and isConnected() needs a new example, do you? 
They are pretty straightforward in their use.

**strange behavior**
Does the sensor get hot? 
What pull ups do you use on the SDA / SCL lines?

**Comment by PetrDa** [comment] 2021-03-30 18:06
I use 10k pullups and I have short distances at this moment. 
Sensor AM2320 dont get hot and as soon as it is re-powered is shows normal values.
Since I am trying to develop fast-loop-self-recovery (level above your) drivers that are also continuosly indicating presence (or non-presence) of the sensor on the i2c bus I was frequently connecting and disconnecting the sensor at the beginnig of the pcb testing. So hopefully it is the reason why now the sensor is malfunctioning. As soon as I finish testing other sensors I replace AM2320 by new one and I will see if other piece is better.

**Comment by RobTillaart** [comment] 2021-03-31 08:01
10K should be good for short distances (up to 25 cm ~ 10 inch), 
I mostly use 4K7 and if wires get beyond 100 cm (40") it use 2K2 or even 1K.
Do you have a oscilloscope to check the signal quality?
If not consider a  JYE Tech DSO150  which is very good for its price and ideal for quick signal check.

Have you checked the datasheet if it states something that could explain it? Text or in a diagram? 
Which I2C bus speed do you use, 100 KHz (default) or higher?

**Comment by PetrDa** [comment] 2021-04-01 14:37
I use default i2c speed 100k.
The 10k pullups are default on pcb when only MCP23017 and AM2320 (that are directly on pcb) are connected. When I add ADS1115, STHT31 and BME280 modules, each of them has own 10k pullups. So in full config thre are 4 pullups each 10k, that makes 2k5 which is optimal. And cable lengths are 0-10cm now white testing this pcb. 
I have practical experience with previous pcb board with ESP8266, PFC8574 expander on the pcb and 4 additonal sensors:
BME280 on 1 meter cable, BME 280 on 6-meter cable and two SHT31 on 2-meter cable each. It is working without any CRC failure detection even with higher speeds. 
So I think that pullups or i2c speed is not an issue.
(nore ideas in next entry in a moment....)

**Comment by PetrDa** [comment] 2021-04-01 15:10
I have looked at the i2c bus with the salae analyser and captured analog and digital values there.
I have captured AM2320 communication when it was ok after power-up and its failed communication after few hours. And also I have captured MCP23017, SHT31, ADS115 and BME280 communication on the same bus for comparison.
All this data including the textual output from I2C analyser in xlsx file are zipped in this file for download:

https://gopascz-my.sharepoint.com/:u:/g/personal/petr_daniel_gopascz_onmicrosoft_com/EVmamu-Fd1lIibfBnH98WhwBXyQKM-A_-sXb6z5r89HPGw?e=w5NKiu

The link is valid for one month and the file has about 26MB, each capture is 10 or 20 milliseconds. 
To open the captures you have to use OLD version of Logic1 app from Salae, available for download here:

https://support.saleae.com/logic-software/legacy-software/older-software-releases
(In case you did not used the old version, here is the help:
https://support.saleae.com/user-guide/using-logic/saving-loading-and-exporting-data 
https://support.saleae.com/user-guide/using-logic/using-protocol-analyzers )

It seems to me that after few hours the sensor stops working and stops answering in i2c bus totally.
(I have used another piece from the same aliexpress purchase and it behaves similarly as the first one). 
I may try to buy another piece from local market to find if it behaves differently.

The signals on the i2c bus look normally, but maybe you find some details I have overlooked.

**Comment by RobTillaart** [comment] 2021-04-02 08:23
Cannot guarantee I will find time to dive in all that data, but at least you did a good job collecting it.
(I'm familiar with saleae logic analyzer)

**Comment by RobTillaart** [comment] 2021-04-02 11:39
Had a quick look at the fail picture and I notice the CLOCK signal is not very well timed, when the first byte is send. 
Especially the last pulses are much wider than they should.

Could it be an interrupt in the background, that delays the I2C clock?
Which board do you use?

**Comment by PetrDa** [comment] 2021-04-02 18:32
I use WemosD1 Mini ESP8266 with NRF24+ on pcb, but no interrupts are used. 
It is interesting that first clock signal is slow, but in later repetitions clock is faster (but I have  no experience with ic2 timing).
I also tried to change i2c clock but the results were same from 50k to 400k frequency.

Anyway I have ordered few other AM2320 sensors from local supplier.  It should take less than one week to get them.
So I test first other sensors before I invest some more time into investigations of this problem.

**Comment by RobTillaart** [comment] 2021-04-03 06:15
#### AM2320 - OK
- four spikes at the falling edge of the SCL

#### AM2320 - FAIL
- very long first pulse in SCL
- there is also a small delay in the last bit of the first byte

#### SHT31- signal
- in the data signal one can see a (minimal) echo of the SCL line on the SDA line. (others have this too)
- there is also a small delay in the last bit of the first byte

#### MCP23017
- two unexpected pulses on the SDA line, they are on the falling edge of the clock. Can't explain, apparently no error.
- small delay in the last bit of the first byte

#### BME 280
- small delay in the last bit of the first three bytes

#### ESP8266
- is a 3.3V device 
- high levels of SCL and SDA appear at ~3.1 max  This is at the edge of the spec of the chip. (see datasheet attached)
- looks like a serious candidate for the root cause


#### Final thoughts
- there are unexplained spikes that definitely should not be there. 
  - Could be a wiring ?
  - Soldering ?
- there is unexplained timing on the SCL. This also happens with the other devices. 
  - The AM2320 might be just more sensitive?
- the AM2320 is operating at the lower edge of its voltage range 
  - did not check the datasheets of the other devices.
  - check if the sensor(s) get 3.3V on their VDD
- Do a 24++ hour test with a 5V processor to confirm that 5V is more stable

==>  use a bidirectional 3.3 <> 5V level converter for I2C bus.
you might split the I2C bus in a 3.3V part and a 5V part.

[AM2320.pdf](https://github.com/RobTillaart/AM232X/files/6252024/AM2320.pdf)

**Comment by RobTillaart** [comment] 2021-04-12 10:50
@PetrDa 
Any progress?

**Comment by PetrDa** [comment] 2021-04-12 11:16
I am working on it, but I would like present some reasonable findings rather than a fog of hypotheses. Give me few more days...

**Comment by RobTillaart** [comment] 2021-06-07 15:35
@PetrDa 
Any progress?

**Comment by RobTillaart** [comment] 2021-07-04 18:12
@PetrDa
Any progress?

**Comment by PetrDa** [comment] 2021-07-04 22:44
Hi Rob, I had to finish other project during last three months, but I was working on this issue in background mode. The testing was very lenghty since failure happened not immediately but after few days. At the moment it seems I have stable program reading values for 30+ days from one of sensors, and now testing the other sensor from different source if it is also stable. 
There is a small problem since I have running solution but I am not sure what was the cause of the problem. Therefore I will have to go back through previous code versions and find the point when reading fails again. 
This month I am traveling so I hope I get to this topic back in August.

**Comment by RobTillaart** [comment] 2021-07-05 05:00
Good to hear there is some progress made.

**Comment by RobTillaart** [comment] 2021-08-24 08:46
Any progress made?

**Comment by nanofortran** [comment] 2021-09-05 17:13
Been following this thread, I too am running at 3.3v and maybe this is the problem, who knows? I am about to redesign around another component that does not sleep. Anyway, thought I would bump the thread and see if there were any software solutions for resetting this sensor. For me, I have to hard reset (power down/up) to get the sensor to begin functioning correctly again.

**Comment by RobTillaart** [comment] 2021-09-05 18:41
>  I too am running at 3.3v and maybe this is the problem, who knows?

thought about that too

> ESP8266
is a 3.3V device
high levels of SCL and SDA appear at ~3.1 max This is at the edge of the spec of the chip. (see datasheet attached)
looks like a serious candidate for the root cause

Maybe it is possible to connect the sensor itself with 5V but keep the SDA/SCL signals at 3V3.
The 5V could help to give sharper edges to the pulses - maybe use small pull ups (1K?) to improve the pulses..
(did not investigate BTW)

**Comment by PetrDa** [comment] 2021-09-06 14:35
To power AM2320 by 5V was one of first things I made, but there was no difference. I did not set pullups to 5V since I have more i2c devices on the bus and they powered by 3v3 so I did not want to risk higher bus inputs than their power supply.

@nanofortran: Do you experience the same failures in your case (or only following this thread)? If yes, what other i2c devices do you have on the bus? I also found thet the only way how to reset the sensor is power it off and on. (In the final project I need to implement before winter I plan to power this sensor from ESP output D0 to be able to reset it after it fails. (This works perfectly in other project for DHT21 that fails after ESP reset when it is connected to D4 as data).  

(Sorry for longer mute from my side, but the pain in back and hand prevented me to spend more time with computer than it is necessary for my job. I am not totally idle, I am runnig long term sensor test (failure after 31 days, then failure after 11 days, now still ok after 28days). It gets better so during September I hope I make some advance.)

**Comment by RobTillaart** [comment] 2021-09-06 15:05
@PetrDa 
Thanks for the update, 
how often do you sample the sensor?

**Comment by PetrDa** [comment] 2021-09-06 19:00
I read AM2320 every 10 seconds, the same period as I read SHT31 and BME280 on the same bus. There is also MCP23017 on this bus and I read its inputs every 50 milliseconds.

**Comment by PetrDa** [comment] 2021-09-15 20:30
At the first look yes. But when the node is at a remote location (100 km distant) so to reset it every month is not very convenient. Moreover other sensors (SHT31 and BME280) sitting on the same bus did not failed at all from April.

The failure of AM2320 is somehow correlated with presence and i2c bus traffic of MCP23017. I use your driver MCP23017_RT but in the meantime I have improved it in my local copy. I created the fork of MCP23017_RT v.0.2.3 on GitHub today and copied my changes into this fork and I make pull request and explain what I suggest to change.

**Comment by RobTillaart** [comment] 2021-09-16 07:59
OK, 100 Km is pretty remote.

Did you consider to build in a watchdog in the code so if it locks it resets the system from hardware?
An RTC and FRAM could help to keep state.

**Comment by PetrDa** [comment] 2021-09-16 10:47
As I mentoned earlier, in the final system I will power AM2320 from D0 of the ESP. It allows me to restart the sensor as soon as it fails. I will record these events during whole winter so I will have good statistics.
(I use AM sensor at the PCB to monitor temp and hum in the box of the node, so I am able to power it from other source than rest of the i2c bus that will powers all other sensors. But at the moment AM is powered as all other sensors.)

**Comment by RobTillaart** [comment] 2021-09-16 11:07
> I will power AM2320 from D0 of the ESP. 

I assume with some extra transistor / mosfet - don't know how much power it draws?
also allows to use less energy.

**Comment by PetrDa** [comment] 2021-09-16 11:24
Since I do not use AM heater in my code I plan to connect D0 directly to Vdd maybe with 100nF capacitor. It works well with DTH21 in other system where DHT data line is connected to D4. 
As I mentioned I test it over winter and then I evaluate (and improve if necessary), this node is not critical, now it will only monitor temperature in the weekend house cellar over this winter, I plan to add more connected devices to i/o next year.

**Comment by RobTillaart** [comment] 2021-11-14 09:32
Please reopen when needed. (I have too much dangling issues so I'm closing some)

**Closed by RobTillaart** 2021-11-14 09:32 UTC
Labels: question
